### ISSUE TITLE
Upload alignment marked "critical" does not work via GUI

### ISSUE THREAD

**Issue by sonjafoerster** [int-brain-lab/iblapps#108]
Dear Mayo (I suppose it'll be you taking this ;) )

**Issue description**
When I try to upload an alignment with QC for ephys recording set to "critical", the upload process is not initiated and the alignment won't upload. Instead, an error message is thrown in the terminal: TypeError: main_gui() got an unexpected keyword argument 'eid'

**Steps to reproduce**
1. Do alignment in GUI
2. Click _Upload_-button
3. Under _QC for ephys recording_-dropdown, select _Critical_
4. Select any metrics under _Confidence of alignment_-dropdown as well as _Describe problem with recording_-section
5. Click _OK_-button

**Screenshots**
1. Upload Dialog (example) 
![CSHL068_20201005_probe01_right_alignment2_correctInsertion_update20240109_uploadDialogCritical](https://github.com/int-brain-lab/iblapps/assets/115865966/8b7a2d2e-196f-46b9-8f6b-da593b29d3bd)

2. Error message (full text)
<img width="1023" alt="CSHL068_20201005_probe01_right_errorMessage_uploadDialogCritical_20240109" src="https://github.com/int-brain-lab/iblapps/assets/115865966/a559138b-e0c3-4dd1-b52e-3670dcdac8c2">

Thanks in advance for your help.
Best,
Sonja

**Comment by mayofaulkner** [comment]
Hi Sonja,

Thanks for pointing out that error! I've fixed the code on both develop and master branch of iblapps. You will need to run the alignment again for this session that failed, sorry about that.

Mayo

**Comment by sonjafoerster** [comment]
Awesome, Mayo, thanks a lot for your prompt support. It now works!
