### ISSUE TITLE
Error launching Gui - External user2

### ISSUE THREAD

**Issue by imontiel92** [int-brain-lab/iblapps#113]
Dear IBL,
When I run the script:
`python int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py`
Nothing happens. No window appears. Any idea how I could fix it?
Thank you very much.

**Comment by mayofaulkner** [comment]
Hi could you try launching in the same way but using ipython. Also you will need to run it in offline mode so don't forget to add the `-o True` argument

e.g
`ipython int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py -o True`

Let me know if that works

**Comment by mayofaulkner** [comment]
It looks like you haven't selected any data. You need to click on the `...` button and then navigate to the sample data folder. More instructions here https://github.com/int-brain-lab/iblapps/wiki/2.-Usage-instructions#external-users

**Comment by imontiel92** [comment]
I have clicked on the button ..., but no file appears.
I have tried with my data and with the test data that you provide us, which is inside the ephys_alignment_sample_data.zip folder.
![error_image_4](https://github.com/int-brain-lab/iblapps/assets/126781302/7036a379-2b62-46f3-a55a-19204b5ab5db)

**Comment by mayofaulkner** [comment]
It may be that the files contained within that directory don't display in the file widget. If you select that folder though and then press get_data it should work

**Comment by imontiel92** [comment]
Great. Now it works. Thank you so much.

**Comment by mayofaulkner** [comment]
Great! I'll close this issue! Feel free to reopen if you have other problems :)
