### ISSUE TITLE
SHARP-Track tool equivalence

### ISSUE THREAD

**Issue by imontiel92** [int-brain-lab/iblapps#115]
Hello,

I would like to use the GUI, but I only processed my images using the SHARP-Track tool because my images were captured using a 2D ApoTome microscope. What can I do? Can I still use the GUI? 

Thank you in advance.

Ivan

**Comment by imontiel92** [comment]
Hello (again)
![ibl_analysis](https://github.com/int-brain-lab/iblapps/assets/126781302/2bc2e7c3-7c20-41bd-997e-e686d3ea8199)
![ibl_analysis_2](https://github.com/int-brain-lab/iblapps/assets/126781302/1d534a25-228f-4cf8-819f-e9a0d548b870)


I successfully installed the IBL alignment tool 🥳. However, while the GUI can recognize the ephys data, the histology data presents a problem. As shown in the top right panel, the probe is completely outside. I have run the scripts that you posted here: (https://github.com/int-brain-lab/iblapps/issues/88 and https://github.com/int-brain-lab/iblapps/issues/83) but they are not working with my data.

I would greatly appreciate any ideas or suggestions you can provide.

Thank you in advance,

Ivan

**Comment by mayofaulkner** [comment]
Hello! That's great to hear! It looks like it is to do with the conversion of the mlapdv coordinates from Sharp track to the IBL convention. Do you know what the default convention from sharp track is? Resolution, ordering e.g (mlapdv) If you have an example of the output you use from Sharp track and I can also take a look :)

**Comment by imontiel92** [comment]
Hello,
Thank you very much for your assistance! :)
The resolution is 10 µm.
The ordering is AP, DV, ML.
Please find attached an example of the data.

Thank you (again)!

**Comment by mayofaulkner** [comment]
Hello, so I used basically the same code as in the solution to #83 and was able to get your coordinates in the correct format.

Here is the code I used 

```
from iblatlas.atlas import AllenAtlas
import numpy as np
from pathlib import Path
import json

res = 10
brain_atlas = AllenAtlas(res)


probePoints = pd.read_csv(r'pathToPoints\0_probe_points.csv')
ccf_mlapdv = np.array(probePoints, dtype=np.float64) * res
bregma_mlapdv = brain_atlas.ccf2xyz(ccf_mlapdv, ccf_order='mlapdv') * 1e6

xyz_picks = {'xyz_picks': bregma_mlapdv.tolist()}

output_path = Path(r'myPath\int-brain-lab\exp_data')
with open(Path(output_path, 'xyz_picks.json'), "w") as f:
    json.dump(xyz_picks, f, indent=2)

```
The traced line is from Sharp Track looks quite jagged so I would recommend putting a best fit line through it and redistributing your points along this line before aligning

<img width="415" alt="Screen Shot 2024-03-14 at 4 41 43 PM" src="https://github.com/int-brain-lab/iblapps/assets/11440465/722e7780-3604-4279-89e4-19cc6a79837d">

Let me know if that works for you :)

**Comment by imontiel92** [comment]
Excellent! This time the probe is inside the brain :D
![3_ibl](https://github.com/int-brain-lab/iblapps/assets/126781302/bd5b99e4-982e-4f45-bcbf-8deb70b1c316)

But my images show that I reached the hippocampus. What am I doing wrong? Or is it that in this case I didn't actually reach the hippocampus?

![4_ibl](https://github.com/int-brain-lab/iblapps/assets/126781302/37c13142-4462-41d7-afca-e22c5d2edb1a)

On the other hand, how could I redistribute your points along this line before aligning?

Thank you very much for your time and patience

**Comment by mayofaulkner** [comment]
Hello, 

It looks like in your file the ordering was AP, ML, DV. When I swap the first two axis it gives a location that matches with  the image you sent, also in the correct hemisphere now 
<img width="270" alt="Screen Shot 2024-03-15 at 10 05 44 AM" src="https://github.com/int-brain-lab/iblapps/assets/11440465/4f53c001-d201-4f60-816f-a2a7434de9db">

In the code below I also show how you can get a best fit line. You can create an insertion object which basically computes the best fit line through the 3D point cloud that you have and returns the coordinates of the top and bottom points of this line. I then save this as the xyz_picks and this is what the alignment gui will use. Let me know if that helps

```
from iblatlas.atlas import AllenAtlas, Insertion
import numpy as np
from pathlib import Path
import json
import pandas as pd

res = 10
brain_atlas = AllenAtlas(res)


probePoints = pd.read_csv(r'/Users/admin/Downloads/0_probe_points.csv')
probePoints = np.array(probePoints, dtype=np.float64)
# Appears that in the file given order is ap,ml,dv => switch so order is ml,ap, dc
ap = np.copy(probePoints[:, 1])
probePoints[:, 1] = probePoints[:, 0]
probePoints[:, 0] = ap

ccf_mlapdv = probePoints * res
bregma_mlapdv = brain_atlas.ccf2xyz(ccf_mlapdv, ccf_order='mlapdv') * 1e6
# xyz_picks = {'xyz_picks': bregma_mlapdv.tolist()}

# Compute an insertion that passes through the points, line of best fit through the 3D cloud of points
ins = Insertion.from_track(bregma_mlapdv / 1e6, brain_atlas=brain_atlas)
# get the coordinates of the tip and top of the line of best fit and use this as the xyz_picks
xyz_picks = {'xyz_picks': (ins.xyz * 1e6).tolist()}

output_path = Path(r'/Users/admin/Downloads')
with open(Path(output_path, 'xyz_picks.json'), "w") as f:
    json.dump(xyz_picks, f, indent=2)
```

**Comment by imontiel92** [comment]
Hello,
I have good news: The GUI works well! :) I tried it with different animal files, and there are no mistakes. Thank you so much for your time and patience. The GUI is amazing!

**Comment by mayofaulkner** [comment]
Amazing! That's great to hear. You are very welcome. I'll close this issue now, but feel free to reopen or make a new issue if you run into any other problems :)
