### ISSUE TITLE
CSHL055 2020-02-18 probe00

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblapps#25]
Could not upload data from CSHL055 2020-02-18 probe00 using ephys GUI:

![image](https://user-images.githubusercontent.com/32096962/99981926-d9ae5e80-2da1-11eb-8f24-204fb28ae827.png)

in conda prompt:
![image](https://user-images.githubusercontent.com/32096962/99982002-f5b20000-2da1-11eb-9215-09f53ac77e96.png)

**Comment by mayofaulkner** [comment]
This error is related to the temporary expiration of the alyx certificate. It should be fixed now
