### ISSUE TITLE
Installation instructions for external users not working

### ISSUE THREAD

**Issue by peterzh** [int-brain-lab/iblapps#39]
I'm looking to use the atlaselectrophysiology tool, and so I'm following the [instructions for external users](https://github.com/int-brain-lab/iblapps/wiki/1.-Installation#1-create-compatible-python-environment), using the latest develop branch code for ibllib and iblapps. Unfortunately when I try to load the software I get the following error:

```
(iblenv) C:\Users\####\Documents>python int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py -o True
Traceback (most recent call last):
  File "C:\Users\####\Documents\int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py", line 6, in <module>
    from atlaselectrophysiology.load_data import LoadData
  File "C:\Users\####\Documents\int-brain-lab\iblapps\atlaselectrophysiology\load_data.py", line 3, in <module>
    import ibllib.pipes.histology as histology
  File "C:\Users\####\Documents\int-brain-lab\ibllib-repo\ibllib\pipes\histology.py", line 8, in <module>
    from one.api import ONE
ModuleNotFoundError: No module named 'one'
```

It looks like the [recent develop commit](https://github.com/int-brain-lab/ibllib/blob/27838d4b7dba1c24181856cff9c236076fe81ba0/ibllib/pipes/histology.py#L8) ibllib.pipes.histology is importing the module 'one', while in the [recent master commit](https://github.com/int-brain-lab/ibllib/blob/bc29ecb44212d8dd899be987cf407b28e9c0d3be/ibllib/pipes/histology.py#L8), ibllib.pipes.histology uses the module 'oneibl'. 

I'm therefore not sure whether we're supposed to use the develop branch or the master branch for ibllib and iblapps.

**Comment by mayofaulkner** [comment]
Hello,

Sorry about that, we are in the middle of changing around the structure of our modules which is causing the issues. For now, if you use the ibllib master branch the code should work as expected. Let me know if not.

**Comment by peterzh** [comment]
Hi thanks for the quick reply - I reinstalled using the ibllib master branch and I got it working thanks!

**Comment by takacsflora** [comment]
Hi, I pulled changes today and I have the same issue -- checking out on master on ibllib-repo didn't help me. Any ideas?

**Comment by mayofaulkner** [comment]
Hi, please could you try `pip install ONE-api` in your iblenv environment

**Comment by takacsflora** [comment]
Thanks for the quick response! I then get this error:
```
Traceback (most recent call last):
  File "C:\Users\Flora\Documents\Github\ibl-dev\iblapps\atlaselectrophysiology\ephys_atlas_gui.py", line 6, in <module>
    from atlaselectrophysiology.load_data import LoadData
  File "C:\Users\Flora\Documents\Github\ibl-dev\iblapps\atlaselectrophysiology\load_data.py", line 7, in <module>
    from oneibl.one import ONE
ModuleNotFoundError: No module named 'oneibl.one'
```

**Comment by mayofaulkner** [comment]
Could you then make sure you pull the latest changes from both iblapps and ibllib-repo repositories

**Comment by takacsflora** [comment]
thanks for the rapid help, I am getting there! Now the gui seems to work with my old P3B tracks, but I get [this ](https://github.com/int-brain-lab/iblapps/issues/51)error when trying to convert any new data (tried both P3B and 2.0). Thanks for the help again!

**Comment by mayofaulkner** [comment]
So I fixed that on the develop branch of ibllib-repo. Can you make sure go back to the develop branch of ibllib-repo and pull the latest changes.
