### ISSUE TITLE
Preparing Kilosort v3.0 data for ephys GUI

### ISSUE THREAD

**Issue by peterzh** [int-brain-lab/iblapps#40]
The [code snippet](https://github.com/int-brain-lab/iblapps/wiki/4.-Preparing-data-for-ephys-GUI#preparing-ephys-data) provided to convert kilosort output seems to be compatible only with kilosort v2. When I run on kilosort v3.0 data I get errors which arise because the called methods are unable to get an estimate of spike depths, which I think is due to v3.0 not saving pc_features.npy or pc_features_ind.npy files relied on to compute depths.

Given this, is there any way to convert Kilosort v3.0 data into a format compatible with the ephys GUI?

Thank you

**Comment by mayofaulkner** [comment]
Hello,

Could you post the error message that you get when converting the files. The code should run through without errors, however, because it does not have the pc_features the output spikes.depths will contain be a fixed depth for each cluster across time. 

I'm afraid I am not very familiar with the KS3. Is there an output that gives an estimate of the depth of the clusters across the recording?

**Comment by peterzh** [comment]
When I run the code snippet on KS3 data I get the following error:
```
(iblenv) C:\KS_spikeSorting>python CONVERT_KS2.py
Traceback (most recent call last):
  File "C:\KS_spikeSorting\CONVERT_KS2.py", line 13, in <module>
    extract_data(ks_path, ephys_path, out_path)
  File "C:\Users\####\Documents\int-brain-lab\iblapps\atlaselectrophysiology\extract_files.py", line 126, in extract_data
    ks2_to_alf(ks_path, ephys_path, out_path, bin_file=efile.ap,
  File "C:\Users\####\Documents\int-brain-lab\iblapps\atlaselectrophysiology\extract_files.py", line 116, in ks2_to_alf
    ephysqc.spike_sorting_metrics_ks2(ks_path, m, save=True)
  File "C:\Users\####\Documents\int-brain-lab\ibllib-repo\ibllib\ephys\ephysqc.py", line 237, in spike_sorting_metrics_ks2
    c, drift = spike_sorting_metrics(m.spike_times, m.spike_clusters, m.amplitudes, m.depths)
  File "C:\Users\####\Documents\int-brain-lab\ibllib-repo\brainbox\metrics\single_units.py", line 848, in spike_sorting_metrics
    df_units = quick_unit_metrics(
  File "C:\Users\####\Documents\int-brain-lab\ibllib-repo\brainbox\metrics\single_units.py", line 995, in quick_unit_metrics
    depths = spike_depths[ispikes]
TypeError: 'NoneType' object is not subscriptable
```

After doing some digging this is caused by spike_depths being set to None within [phylib.io.model](https://github.com/cortex-lab/phylib/blob/3e4dfb9be8caead2d82b38c842b3fddbc84cf59a/phylib/io/model.py#L1043) because pc_features is absent for KS3 data. And it looks like your cluster metrics requires values to be defined for spike_depths. For some reason the code does not currently set a fixed depth for each cluster across time, if pc_features is absent.

**Comment by peterzh** [comment]
In case this is useful I have written the following script to perform the same kind of conversion in a way that's compatible with KS3.0 data. This script works for me now, thanks!

```
from pathlib import Path
from ibllib.io import spikeglx
from atlaselectrophysiology.extract_files import extract_data, extract_rmsmap, _sample2v 
import ibllib.ephys.ephysqc as ephysqc
from phylib.io import alf
import numpy as np

# Path to KS2 output
ks_path = Path(r'C:\KS_spikeSorting')

# Path to raw ephys data
ephys_path = Path(r'C:\KS_spikeSorting')

# Save path
out_path = Path(r'C:\KS_spikeSorting\output')

# STEP 1: Load KS data and convert to ALF files
ap_bin_path = list(ephys_path.glob('**/*.ap.bin'))[0]
lf_bin_path = list(ephys_path.glob('**/*.lf.bin'))[0]
m = ephysqc.phy_model_from_ks2_path(ks_path, ephys_path, ap_bin_path)
ac = alf.EphysAlfCreator(m)
ac.convert(out_path, force=True, ampfactor=_sample2v(efiles[0].ap))

# STEP 2: SAVE AP & LF RMSMAP
efiles = spikeglx.glob_ephys_files(ephys_path)
extract_rmsmap(ap_bin_path, out_folder=out_path, spectra=False)
extract_rmsmap(lf_bin_path, out_folder=out_path)

# STEP 3: Cluster metrics, using the spike depths computed already
spike_depths = np.load(out_path / 'spikes.depths.npy');
m.depths = spike_depths
ephysqc.spike_sorting_metrics_ks2(ks_path, m, save=True)

print('All done')
```

**Comment by mayofaulkner** [comment]
Thanks for sharing this!
