### ISSUE TITLE
installation error with SSL certificate_verify_failed

### ISSUE THREAD

**Issue by zhiwen10** [int-brain-lab/iblapps#44]
Hi Mayo,
I'm testing the Ephys Atlas GUI.  On one windows PC, error messages were thrown back as in the following snapshot. 
I tried 'External User installation instruction' on wiki and 'the UCL Neuropixels Course 2020 manual', both returned same errors.  However, installing in a different Windows PC, both methods had no problem. Not sure how prevalent this issue is among users, thought it might be useful to post here if you have any quick solutions.

For `qt.qpa.fonts: Unable to open default EUDC font: "EUDC.TTE"`, I can easily fix this by editing  \HKEY_CURRENT_USER\EUDC\1252 (1252 is the code of the latin alphabet) "SystemDefaultEUDCFont" key value to "C:\Windows\Fonts\seguibli.TTF" (for Segoe UI font). Not sure about the rest.

![installationError](https://user-images.githubusercontent.com/24544991/135956636-2185c304-62a8-4f15-a350-9c16ad45d7bc.JPG)

Zhiwen

**Comment by mayofaulkner** [comment]
Hi Zhiwen,

I've been struggling with this error on some windows computers and haven't yet got to the bottom of the issue. For now the best way I have found to get around this error is to first do the following in an ipython terminal
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
from one.api import ONE
ONE(silent=True, password='international')
```
and then launch the gui as normal using
`python ephys_atlas_gui.py -o True`

Let me know if that works and I will continue to look into the cause of the problem.

Mayo

**Comment by zhiwen10** [comment]
Hi Mayo, this workaround provided worked for me. Thank you!
