### ISSUE TITLE
AttributeError: 'PlotData' object has no attribute 'spike_idx' in example dataset

### ISSUE THREAD

**Issue by zhiwen10** [int-brain-lab/iblapps#45]
Hi Mayo,
I'm helping with homework assignment at UCL Neuropixels Course this year. We are using this GUI as homework 3. It's much easier right now if we can use your wiki link as the instruction guide. I noticed an error message after loading the example dataset `ephys_alignment_sample_data.zip ` at [this link]( https://ibl.flatironinstitute.org/public/). Error message is as below. Could you fix this?
Thanks,
Zhiwen

![CaptureIBL](https://user-images.githubusercontent.com/24544991/136314044-fafda0ab-1e3b-43de-83c8-1036e51a4dfe.PNG)

**Comment by zhiwen10** [comment]
Great. Thanks. I'm also testing on a Mac system. Installation was successful, but the GUI was not launching after running the command line. It seems like it got stuck there without error messages. I wonder if this was observed previously, or just due to my local setup. It's hard to debug due to a lack of error message perhaps. Is the GUI used often on Mac and Linux by current users, in your knowledge? It might be useful to mention to attendees if it's not widely tested on Mac or Linux.

**Comment by mayofaulkner** [comment]
Within the IBL we have quite a few Mac and Linux users who are running it without problems. Which mac operating system are you? Could you try running this in your terminal before launching the gui `export QT_MAC_WANTS_LAYER=1` (taken from this stack exchange thread https://stackoverflow.com/questions/64833558/apps-not-popping-up-on-macos-big-sur-11-0-1#_=)

**Comment by zhiwen10** [comment]
My Mac is indeed the upgraded Big Sur. This solution worked as well. Awesome!

**Comment by zhiwen10** [comment]
Just saw this on wiki instruction. Please ignore last message.
