### ISSUE TITLE
Adapting atlaselectrophysiology for 4-shank Neuropixels 2.0

### ISSUE THREAD

**Issue by alowet** [int-brain-lab/iblapps#48]
This isn't a bug report but rather a feature request (sorry that I couldn't find a better place to post it). As you may know, imec released a version of Neuropixels 2.0 which has 4 shanks. It is often the case that I record on all four shank at once, meaning that there are only 96 channels per probe track. Further, many of the channels near the tip of the probe have high channel numbers, and so would not appear at the tip with the default channel mapping. Is there a way to adapt atlaselectrophysiology such that it uses the IMRO table from SpikeGLX or the x/y coordinates from Kilosort to redefine the probe geometry? Even a workaround that allowed me to select which channels to use and where to place them (e.g. at the tip), while ignoring all other channels, would be immensely helpful — even if it meant registering only one shank at a time. I can always dig around in the guts of atlaselectrophysiology myself, but I thought I should ask in case something like this is already under development, or you have a good intuition for how to incorporate it without too much trouble. Thanks for the excellent toolbox!

**Comment by mayofaulkner** [comment]
Hello, it is now possible to use the alignment tool with Neuropixel 2.0 probes with different geometries.

For the 4 shank probes there are two ways in which it can be used depending on how the data has been spikesorted,

Option 1: All 4 shanks spikesorted together
In this case the gui automatically detects the number of shanks from the channels.localCoordinates file and a dropdown menu option allows you to choose which shank to align. The only difference compared to the NP1 case is that the user must provide an xyz_pick file per shank with the naming, xyz_picks_shank1.json, xys_picks_shank2.json etc. So if you have the x y coordinates from kilosort and have successfully converted them to the channels.localCoordinates.npy dataset, it should (in theory) work out the box.

Option 2: Shanks spikesorted individually
In this case the gui acts as it would for a single shank and you only need to provide one xyz_picks.json file as before. A couple things to look out for when preparing the files,
- The channels.localCoordinates must only contain coordinates of the electrodes on the single shank
- If the data files extracted from the raw data e.g _iblqc_ephysTimeRmsAP.rms, _iblqc_ephysTimeRmsLF.rms contain 384 channels, the channels.rawInd.npy file must only contain the correct indices for electrodes on each shank. From matlab kilosort this can be found from the connected map (find(connected))
- If the data files extracted from the raw data e.g  _iblqc_ephysTimeRmsAP.rms, _iblqc_ephysTimeRmsLF.rms   have also been split per probe and contain 96 channels then the channels.rawInd.npy should just be the equivalent of np.arange(96)

Please make sure you are on the develop branch of both iblapps and ibllib-repo and have pulled the latest changes.

Let me know if that helps and if you run into any problems :)

**Comment by alowet** [comment]
Hi there,

The changes on the develop branch work great! I used option 1, for all 4 shanks spike sorted together. Thank you so much for the pointers, and for this excellent package in general!

FYI, I had to make a few tweaks to the code (this pre-dated the NP2 developments) to make it work for me. In particular, I believe that the code as written does not allow for clusters that have been manually merged in Phy, such that the cluster_ids no longer match perfectly with the template_ids. If it's helpful for you/this is a bug you're not aware of, I can make a pull request with my revisions, so let me know.

Another observation: it appears that channel_locations_shank1.json, channel_locations_shank2.json, etc., each are indexed as channel_0 through channel_N (95, in my case). In future, it would be helpful if each of these were indexed with their actual channel number from the original probe, so that they can be easily cross-referenced and/or merged into a single file. But I can also do this manually on the back end.

**Comment by mayofaulkner** [comment]
Hello, sorry for the late reply. 
If you could make a PR with the code that you have for being able to deal with manually merged clusters that would be great. Thank you so much.

Re the second point, I will take a look and add in an extra key in the dict that is saved that has the actual channel index from the recording. I'll let you know when that is implemented

**Comment by alowet** [comment]
Now it's my turn to apologize for the delay!

I finally got around to doing this only to realize that the bug arises not in this package but rather in phylib (get_depths function within io/model.py). So the PR doesn't belong here. Since so many other packages rely on phylib, I figure it'd probably do more harm than good for the general user. Sorry about that!

However, I did notice a different bug which I was able to patch. For four-shank NPX, the first "Upload" would write to the correct file, but if I kept the window open and attempted a different "Upload", it would always (over)write to channel_locations_shank1.json, even if a different shank was selected. I believe this has now been fixed in my PR.

**Comment by mayofaulkner** [comment]
Hello,
Just to let you know that phylib now supports conversion after the clusters have been merged so it is possible to convert data into the format for the GUI after merging in phy.

I have also integrated the changes to fix the bug for the four shank probes. Thanks for pointing that out.

I will close this issue now but feel free to reopen if you run into any other problems :)
