### ISSUE TITLE
extract_data underscores problem

### ISSUE THREAD

**Issue by xy103** [int-brain-lab/iblapps#52]
Hi I'm experiencing the following problem when running extract_data. The code was able to run untill 99.7% complete. I have pulled the most recent iblapps and iblenv repos. Any help would be really appreciated. Thanks!
------------------------------------------------------------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_22036/3265967735.py in <module>
      8 out_path = Path(r'D:\DATA\Depth')
      9 
---> 10 extract_data(ks_path, ephys_path, out_path)

~\Documents\int-brain-lab\iblapps\atlaselectrophysiology\extract_files.py in extract_data(ks_path, ephys_path, out_path)
    130                        ampfactor=_sample2v(efile.ap), label=None, force=True)
    131 
--> 132             extract_rmsmap(efile.ap, out_folder=out_path, spectra=False)
    133         if efile.get('lf') and efile.lf.exists():
    134             extract_rmsmap(efile.lf, out_folder=out_path)

~\Documents\int-brain-lab\iblapps\atlaselectrophysiology\extract_files.py in extract_rmsmap(fbin, out_folder, spectra)
     92         out_folder.mkdir()
     93     tdict = {'rms': rms['TRMS'].astype(np.single), 'timestamps': rms['tscale'].astype(np.single)}
---> 94     alfio.save_object_npy(out_folder, object=alf_object_time, dico=tdict)
     95     if spectra:
     96         fdict = {'power': rms['spectral_density'].astype(np.single),

~\anaconda3\envs\iblenv\lib\site-packages\one\alf\io.py in save_object_npy(alfpath, dico, object, parts, namespace, timescale)
    544     out_files = []
    545     for k, v in dico.items():
--> 546         out_file = alfpath / spec.to_alf(object, k, 'npy',
    547                                          extra=parts, namespace=namespace, timescale=timescale)
    548         np.save(out_file, v)

~\anaconda3\envs\iblenv\lib\site-packages\one\alf\spec.py in to_alf(object, attribute, extension, namespace, timescale, extra)
    375         raise ValueError('Namespace must not contain extra underscores')
    376     if object[0] == '_':
--> 377         raise ValueError('Objects must not contain underscores; use namespace arg instead')
    378     # Ensure parts are camel case (converts whitespace and snake case)
    379     object, timescale = map(_dromedary, (object, timescale))

ValueError: Objects must not contain underscores; use namespace arg instead

**Comment by mayofaulkner** [comment]
Hi, thanks for pointing out this error. I have pushed a change to iblapps develop branch. If you could try again and hopefully it will have solved the problem. Let me know if not.

Many thanks

**Comment by xy103** [comment]
It's working now. Thank you Mayo!
