### ISSUE TITLE
Unable to upload alignments

### ISSUE THREAD

**Issue by chryspapadim** [int-brain-lab/iblapps#56]
Hello! I'm working with Anne Urai on ephys alignments, and have already completed and succesfully uploaded 20 alignments. For the past two weeks I am unable to upload any of my alignemnts, regardless of mouse or session. 

I can download the data, do the alignment, I attempt to upload them and the error I attached always appears.

Let me know if there is anything I can do to resolve this :-)

![AlignmentError](https://user-images.githubusercontent.com/95908694/153879053-9c292847-168b-4442-b5ee-e6d6de874a27.png)

**Comment by mayofaulkner** [comment]
Hi, could you make sure that you are up to date on both iblapps and ibllib-repo develop branches and see if you still have the same error

**Comment by chryspapadim** [comment]
I did update everything, as suggested on Friday using these lines of code:

conda activate iblenv
cd ./ibllib-repo
git pull
cd ../iblapps
git pull
pip install -U ONE-api

I made sure ONE was at version 1.8.0 and tried uploading again, and I was still getting the same error.

**Comment by mayofaulkner** [comment]
Could you also make sure that you don't have an old version of ibllib installed by mistake. This can be done by doing the following 
```
conda activate iblenv
pip uninstall ibllib
```
