### ISSUE TITLE
TypeError conversion issue

### ISSUE THREAD

**Issue by mschottdorf** [int-brain-lab/iblapps#65]
Dear IBL team,

I have a neuropixel dataset, processed with kilosort (latest version, hash `1a1fd3a`). When running the conversion script, ` extract_data` from `atlaselectrophysiology.extract_files` (from the `develop`  branch, hash `d3ff5f0`, I stumbled into this TypeError:

```
In [6]: extract_data(ks_path, ephys_path, out_path)
   ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 extract_data(ks_path, ephys_path, out_path)

File ~\Desktop\int-brain-lab\iblapps\atlaselectrophysiology\extract_files.py:134, in extract_data(ks_path, ephys_path, out_path)
    132 for efile in efiles:
    133     if efile.get('ap') and efile.ap.exists():
--> 134         ks2_to_alf(ks_path, ephys_path, out_path, bin_file=efile.ap,
    135                    ampfactor=_sample2v(efile.ap), label=None, force=True)
    137         extract_rmsmap(efile.ap, out_folder=out_path, spectra=False)
    138     if efile.get('lf') and efile.lf.exists():

File ~\Desktop\int-brain-lab\iblapps\atlaselectrophysiology\extract_files.py:124, in ks2_to_alf(ks_path, bin_path, out_path, bin_file, ampfactor, label, force)
    116 """
    117 Convert Kilosort 2 output to ALF dataset for single probe data
    118 :param ks_path:
   (...)
    121 :return:
    122 """
    123 m = ephysqc.phy_model_from_ks2_path(ks2_path=ks_path, bin_path=bin_path, bin_file=bin_file)
--> 124 ephysqc.spike_sorting_metrics_ks2(ks_path, m, save=True, save_path=out_path)
    125 ac = alf.EphysAlfCreator(m)
    126 ac.convert(out_path, label=label, force=force, ampfactor=ampfactor)

File ~\Anaconda3\envs\iblenv\lib\site-packages\ibllib\ephys\ephysqc.py:400, in spike_sorting_metrics_ks2(ks2_path, m, save, save_path)
    398 # create phylib `TemplateModel` if not given
    399 m = phy_model_from_ks2_path(ks2_path) if None else m
--> 400 c, drift = spike_sorting_metrics(m.spike_times, m.spike_clusters, m.amplitudes, m.depths)
    401 #  include the ks2 cluster contamination if `cluster_ContamPct` file exists
    402 file_contamination = ks2_path.joinpath('cluster_ContamPct.tsv')

File ~\Anaconda3\envs\iblenv\lib\site-packages\brainbox\metrics\single_units.py:843, in spike_sorting_metrics(times, clusters, amps, depths, cluster_ids, params)
    826 """
    827 Computes:
    828 -   cell level metrics (cf quick_unit_metrics)
   (...)
    840 :return: dictionary of recording qc (keys 'time_scale' and 'drift_um')
    841 """
    842 # compute metrics and convert to `DataFrame`
--> 843 df_units = quick_unit_metrics(
    844     clusters, times, amps, depths, cluster_ids=cluster_ids, params=params)
    845 df_units = pd.DataFrame(df_units)
    846 # compute drift as a function of time and put in a dictionary

File ~\Anaconda3\envs\iblenv\lib\site-packages\brainbox\metrics\single_units.py:989, in quick_unit_metrics(spike_clusters, spike_times, spike_amps, spike_depths, params, cluster_ids, tbounds)
    987 ts = spike_times[ispikes]
    988 amps = spike_amps[ispikes]
--> 989 depths = spike_depths[ispikes]
    991 # compute metrics
    992 r.contamination_alt[ic] = contamination_alt(ts, rp=params['refractory_period'])

TypeError: 'NoneType' object is not subscriptable

```

I would appreciate a helping hand. Not sure where to dig deeper.

Thank you so much!

-Manuel

**Comment by mayofaulkner** [comment]
Hello,

If you are using the latest kilosort version it seems there is an error in the conversion process as the pc_features are not extracted. If you follow the code in this issue https://github.com/int-brain-lab/iblapps/issues/40 you should be able to convert the data. Let me know if you have any problems.

Best,

Mayo

**Comment by mschottdorf** [comment]
Hi Mayo, thanks for the note! I have managed to get it to work, but a few extra steps were required. Do you want me to document them here, or below issue #40 ?  The next person stumbling into this issue might find a few notes helpful

-Manuel

**Comment by mayofaulkner** [comment]
Yes, here would be great. Many thanks!

**Comment by mschottdorf** [comment]
1. Peter's script works great, but there is just a minor issue with `tqdm` in `Atlaselectrophysiology` itself. `Tqdm` does not seem to work in its most recent version. A quick fix is to adjust line 45 of the file `atlaselectrophysiology/extract_files.py`. This line reads `with tqdm(total=wingen.firstlast) as pbar`. Changing it to `with tqdm(total=100) as pbar`, and hardcoding the `pbar.update()` in line 65 will do the trick. If you want, I could file a PR, or you guys just change it when you roll out the next version. One can then run ks3, convert to atlas, and fire up the GUI. Note: The script will take a while.

2. One also has to generate a `xyz_picks.json` file. It might be nice to allow the user to generate a simple `xyz_picks.json` file from within the UI, rather than crashing. Anyway, here is the content that I had used: 
 ```
{"xyz_picks": [[1200, -1000, -0], [1200, -1000, -480], [1200, -1000, -960], [1200, -1000, -1440], [1200, -1000, -1920], [1200, -1000, -2400], [1200, -1000, -2880], [1200, -1000, -3360]]}
 ```

3. One last issue where I would appreciate your input: For reasons that I have not fully understood, the conversion script only works in the *absence* of post-processing in phy, such as merging of clusters. The error thrown is a perceived mismatch of the number of templates with the number of clusters. Is this something one can fix easily?

  ![image](https://user-images.githubusercontent.com/3635994/181072381-0ca4fa38-3bfd-4495-a492-5b913b07cd88.png).

**Comment by mayofaulkner** [comment]
Hi Manuel,

Thanks for this. 
1. Yes that tqdm seems to be a new thing. I fixed it in the code on develop so will release that soon along with a few other changes. 
2. I'm not sure I will be able to allow users to pick the xyz_picks from within the UI as this requires higher resolution slices and also there are already many tools for this. I will make sure the app doesn't crash though if these aren't provided (or at least give an informative error message)
3. At the moment the alf conversion only works for non merged/split clusters. I have made a PR to phylib here https://github.com/cortex-lab/phylib/pull/36 which fixes this problem. It still needs to go through a few rounds of review so won't be released yet but if you can try it out from that branch if you like. Let me know if you run into problems.


Thanks,

Mayo

**Comment by mayofaulkner** [comment]
Alf conversion branch has now been released in the new phylib version (> v.2.4.2) and is implemented by default. Closing this issue, but feel free to reopen if you still have any problems :)
