### ISSUE TITLE
FileNotFoundError:  '...\allen_structure_tree.csv'

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblapps#7]
After updating I cannot open ephys_atlas_GUI, it seems that I have to change somewhere a directory to load _allen_structure_tree.csv_:

FileNotFoundError: [Errno 2] File D:\IBL\Programs\Anaconda3\envs\iblenv\lib\site-packages\ibllib\atlas\allen_structure_tree.csv does not exist: 'D:\\IBL\\Programs\\Anaconda3\\envs\\iblenv\\lib\\site-packages\\ibllib\\atlas\\allen_structure_tree.csv'

![image](https://user-images.githubusercontent.com/32096962/90607652-6a9cf900-e1f9-11ea-8db3-3dcfa67b386c.png)

**Comment by mayofaulkner** [comment]
Using installed version of ibllib, solved by typing `pip uninstall ibllib`
