### ISSUE TITLE
channel # and their coordinates mismatched

### ISSUE THREAD

**Issue by runbogao** [int-brain-lab/iblapps#72]
Hi IBL team,

I have been using Electrophysiology Atlas GUI to locate Neuropixel 1.0 channels. It came across to me that the total channel number generated by the GUI has a maximum of 383 (channel 382). I took a close look at the "channel_location.json" file and found out that it was missing the 192nd channel (channel 191), which is defined as reference channel, and that every channel after channel 191 is shifted forward by 1 (fig. 1). Therefore, the maximum  number is 383, not 384. If we want to  #assign locations to spike clusters (putative neuron) by combining peak_channel information generated by kilosort and x,y,z coordinates of channel from "channel_location.json", we will end up with a mismatch. 

In another scenario  #(fig. 2&3), I have a session that was recorded by a neuropixel probe that had 1 broken channel (78th, channel 77). As a result, "channel_location.json" file had only 382 channels. Meanwhile, channel 77 -189 are actually channel 78-190 in kilosort chanMap.mat file, and channel 190-381 are actually channel 192-383.

I was wondering if there is quick way to fix it within GUI or the pipeline. Otherwise, I can still correct it during postprocessing. Thank you! Look forward to your reply!
![image](https://user-images.githubusercontent.com/107888645/190750454-ae1c032c-811a-4edf-b687-a878db7aba37.png)

![image](https://user-images.githubusercontent.com/107888645/190749785-77e4d89b-d011-494d-898e-2fdb3a407ac3.png)
![image](https://user-images.githubusercontent.com/107888645/190750849-efdac2ef-bd21-4b39-82a5-2d1363190fc8.png)

**Comment by mayofaulkner** [comment]
Hello, sorry for the late reply! Could you provide me with your channels.localCoordinates and channels.rawInd files for these two example cases so I can take a look. In general if these files have all the channels present then the GUI will produce positions for all channels

**Comment by runbogao** [comment]
Hi, thanks for your reply! 
[files.zip](https://github.com/int-brain-lab/iblapps/files/10326045/files.zip)
Attached is the files! Thank you again for being willing to take a look at this issue!

**Comment by mayofaulkner** [comment]
Hi, thanks for attaching those files. I've had a look and it seems that those channels that are missing are already missing in the original channels.localCoordinates file and so that's why they are not assigned. The channels.localCoordinates is a direct conversion of the kilosort output channel_positions.npy. Do you have an idea why they are missing from this file? Could it be to do with the map you are using when kilosorting of the minimum fr setting on the channel?
