### ISSUE TITLE
Extract_data ImportError

### ISSUE THREAD

**Issue by Virginia9733** [int-brain-lab/iblapps#75]
Hi there, I encountered error when trying to extract_data for the GUI.

ImportError: cannot import name 'print_progress' from 'ibllib.misc'

I activated the iblenv, cd to the folder containing iblapps, then 
![Screenshot 2022-11-25 135812](https://user-images.githubusercontent.com/61534754/203904554-74cba0ef-54a8-4a12-9fde-310bf243da0a.png)

Many thanks!

**Comment by k1o0** [comment]
Hello, please pull the latest changes on the master branch, that should fix the issue. Feel free to reopen if you're still having problems.
