### ISSUE TITLE
Wrong coordinates for electrophysiology

### ISSUE THREAD

**Issue by AliceBS** [int-brain-lab/iblapps#83]
Hi,

Thanks for designing this tool. I have been trying to use it with probes aligned on allenCCF SHARP-Track (https://github.com/cortex-lab/allenCCF/wiki) and I cannot seem to be able to get the correct coordinates.

I have my data as AllenCCF coordinates, in ML/AP/DV order, with a resolution of 10um and I am using this code to transfer them to bregma coordinates

```
import ibllib.atlas as atlas
import numpy as np
from pathlib import Path
import json
import csv

res = 10
brain_atlas = atlas.AllenAtlas(res)

with open(r'pathToPoints\probe_points_session.csv', newline='') as csvfile:
    probePoints = list(csv.reader(csvfile))
ccf_mlapdv = np.array(probePoints, dtype=np.float64)
bregma_mlapdv = brain_atlas.ccf2xyz(ccf_mlapdv, ccf_order='mlapdv')

xyz_picks = {'xyz_picks': bregma_mlapdv.tolist()}

output_path = Path(r'myPath\int-brain-lab\exp_data')
with open(Path(output_path, 'xyz_picks.json'), "w") as f:
    json.dump(xyz_picks, f, indent=2)
```
It works fine but when I get to the data, the electrode is outside of the brain:

![EphysAtlasBug](https://user-images.githubusercontent.com/47528362/218501578-cfd4781a-e9c6-4ee7-843a-cad565e4d0c6.jpg)

This seems to be the right angle for our probe but not the right origin point, in all directions.
I thought that the problem might be the bregma coordinates, as in the allenCCF SHARP-Track tool the bregma coordinates are 570/540/0 in ML/AP/DV. I tried solving that by adding an offset in the DV dimension but it did not change much. 
I also tried multiplicating the ccf_mlapdv matrix by 1e6 as I saw for the lasagna tool, it improves the location but it still does not give the right coordinate and I am not sure if it is correct for my data. Do you have an idea of what could be going wrong?

Thanks,
Alice

**Comment by mayofaulkner** [comment]
Hello, 

Would you mind attaching the output that you get from SHARP track so I can play around and see what conversion might me needed?

Many thanks,
Mayo

**Comment by AliceBS** [comment]
Of course. The original output is a matlab file containing multiple probes, I just wrote the matrix for this probe to CSV and changed the column order to put the coordinates in ML/AP/DV to get this file.
[probe_points_session.csv](https://github.com/int-brain-lab/iblapps/files/10731022/probe_points_session.csv)

Thanks!

**Comment by mayofaulkner** [comment]
Hello, so I have figured out the issue. The first is that the coordinates given out by SHARP track are in pixels so need to be multiplied by 10 to get them into um. The second is that the ccf2xyz gives out coordinates relative to bregma in metres but the GUI expects um. If you run the following code you should get the electrode track in the correct position

```
import ibllib.atlas as atlas
import numpy as np
from pathlib import Path
import json
import csv

res = 10
brain_atlas = atlas.AllenAtlas(res)

with open(r'pathToPoints\probe_points_session.csv', newline='') as csvfile:
    probePoints = list(csv.reader(csvfile))
ccf_mlapdv = np.array(probePoints, dtype=np.float64) * res
bregma_mlapdv = brain_atlas.ccf2xyz(ccf_mlapdv, ccf_order='mlapdv') * 1e6

xyz_picks = {'xyz_picks': bregma_mlapdv.tolist()}

output_path = Path(r'myPath\int-brain-lab\exp_data')
with open(Path(output_path, 'xyz_picks.json'), "w") as f:
    json.dump(xyz_picks, f, indent=2)
```

It appears though that your tracked trace has many discontinuities, perhaps when scrolling through the slices. I would advise making sure these are smoothed out before aligning. 
![image](https://user-images.githubusercontent.com/11440465/219009320-f66847fb-6fb9-4004-8552-09ece1e58b15.png)

Let me know if that helps :) 

Mayo

**Comment by AliceBS** [comment]
Hi,

Thank you very much, it works now and solves everything.
I just have to take the points from the aligned probe rather than the ones I have and I should be able to use it.

Thanks,
Alice

**Comment by mayofaulkner** [comment]
Great! The aligned results of the GUI are interpolated along the original traced track that is input, so if this is kinked then the aligned version will also be.

**Comment by AliceBS** [comment]
Thanks, with the smoothing it works nicely.

**Comment by Virginia9733** [comment]
Hi there, I am trying to convert the probe tracking from AP_histology, and saved a NPY file for each probe.

%%%%%% Code from Andrew Peters %%%%%%%%%%%%%%
% Convert probe_ccf.mat into .npy for IBL ephys alignment
% Pick filename
probe_ccf = load('D:\repos\AP_histology\sample slides\20240326-NPX2.0-Chronic-CA1-DiI\Save Slices\probe_ccf.mat')
probe_ccf = probe_ccf.probe_ccf
coords = probe_ccf.trajectory_coords
%filename = uiputfile('probe_ccf.npy');
filename = 'D:\repos\AP_histology\sample slides\20240326-NPX2.0-Chronic-CA1-DiI\Save Slices\probe_ccf.npy';
% Write probe_ccf coordinates as NPY file
writeNPY(coords,filename)

% Convert probe_ccf.mat into .npy for IBL ephys alignment for each probe
% Pick filename
[filename, path] = uiputfile;
% Write probe_ccf coordinates as NPY file (separately for each probe)
for curr_probe = 1:length(probe_ccf)
curr_filename = sprintf('%s%s_probe%d.npy',path,filename,curr_probe)
writeNPY(probe_ccf(curr_probe).trajectory_coords,curr_filename)
end

After exporting the coordinates for each probe (each shank of NPX2.0), I tried to convert the coordinate in ML/AP/DV, but has some error messages:

(iblenv) d:\repos>python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibllib.atlas as atlas
C:\Users\muhang\miniconda3\envs\iblenv\lib\site-packages\ibllib\atlas\__init__.py:205: DeprecationWarning: ibllib.atlas is deprecated. Please install iblatlas using "pip install iblatlas" and use this module instead
  warnings.warn('ibllib.atlas is deprecated. Please install iblatlas using "pip install iblatlas" and use '
>>> quit()
(iblenv) d:\repos>python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(iblenv) d:\repos>python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import iblatlas
>>> import numpy as np
>>> from pathlib import Path
>>> import json
>>> res = 10
>>> brain_atlas = atlas.AllenAtlas(res)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'atlas' is not defined
>>> brain_atlas = iblatlas.AllenAtlas(res)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'iblatlas' has no attribute 'AllenAtlas'

I cannot upload npy file so I converted into .csv
[probe_ccf.npy_probe1.csv](https://github.com/int-brain-lab/iblapps/files/14921735/probe_ccf.npy_probe1.csv)

**Comment by Virginia9733** [comment]
Also, may I ask does iblapp supports slide scanning images, especially I only registered a few key slices which have the track of the probes using AP_histology.
![8](https://github.com/int-brain-lab/iblapps/assets/61534754/04b48fe8-8357-41d9-bf83-853ea0576fc2)
![9](https://github.com/int-brain-lab/iblapps/assets/61534754/14b75ec0-d35c-435e-9c68-5ca37d33990e)
![10](https://github.com/int-brain-lab/iblapps/assets/61534754/8ea84f4c-9c94-483f-9393-35ef4c008232)
![11](https://github.com/int-brain-lab/iblapps/assets/61534754/f4830531-82ee-4f73-b2d9-33474deff84c)
