### ISSUE TITLE
Import statements fail from within Python

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblapps#9]
I'd like to use iblapps from within Python but this fails and I'm not sure why:
```
  File "C:\Users\User\Documents\Github\iblapps\choiceworld_ephys_qc\choiceworld_ephys_qc.py", line 14, in <module>
    from iblapps import qt
ModuleNotFoundError: No module named 'iblapps'
```

This only works if I call the script directly, i.e `python task_qc.py fb70ebf7-8175-42b0-9b7a-7c6e8612226e`.

**Comment by k1o0** [comment]
I don't understand how but the problem came from the code calling `choiceworld_ephys_qc.py`.  I deleted this file on the TaskQC branch

**Comment by rossant** [comment]
@k1o0 can this be closed?
