### ISSUE TITLE
which one shoud I input, original or smoothed track points?

### ISSUE THREAD

**Issue by chongtianyifa** [int-brain-lab/iblapps#95]
Hi,

I am not sure what kind of points I should feed to GUI in xyz_picks. I have registered the histology images to AllenCCF and traced the track of probes in the images. I then feed these original points from each image (transformed to CCF) to GUI and did the alignment. I then plotted the location of probes in the CCF using x, y, z of all channels in the output file and found that they were discontinuous. Should I fit a line using original histology image points and select some points along the line to feed GUI? Does the GUI try to fit a line? Did you initialize the location of the first channel by finding the closes point along the fitted line? 

Thanks,
Chris

**Comment by mayofaulkner** [comment]
Hi, 

The gui will fit a fit a line that follows the points that you pass in. If the points have discontinuities or jumps then sometimes this can cause problems and in that case I would suggest fitting a line through your points and then sampling along this line and getting some points out. Note before passing the coordinates into the gui you will need to convert from CCF space to the bregma space that we use in the IBL (see here https://github.com/int-brain-lab/iblapps/wiki/4.-Preparing-data-for-ephys-GUI#coordinate-systems)

The location of first channel is taken as 200um from the lowest traced point. This is based on the neuropixel probe layout. It is important therefore, that the first point that you pass in is at the tip of the probe.

Hope that all makes sense, let me know if anything is unclear :) 

Mayo
